### PR TITLE
(feat) Initial setup

### PR DESCRIPTION
**Pull request by mesaugat**
Just adding some dependencies for now.

* tslint
* tslint-config-standard

EDIT: More stuff

* .editorconfig
* .gitignore update
* license file

### CODE REVIEW

**Comment by mesaugat** [comment]
Do we need prettier or is this enough?

**Comment by mesaugat** [comment]
How do you want the folder structure to be like?

Thinking of something like this.

```
core/
bin/
cli/
app/
utils/
package.json
```

Also, I am tempted to use [yarn workspaces](https://yarnpkg.com/lang/en/docs/workspaces/). Each folder will have it's own `package.json` and dependencies.

**Comment by mesaugat** [comment]
Let's leave out prettier. And does prettier-standard work with TypeScript?

**Comment by srishanbhattarai** [comment]
Not sure, lets just not bother with it. This seems good to merge. 👍

**Pull request merged**
